Allow pushing to GAR too

diff --git a/.github/workflows/build-push-ghcr.yaml b/.github/workflows/build-push-ghcr.yaml
--- a/.github/workflows/build-push-ghcr.yaml
+++ b/.github/workflows/build-push-ghcr.yaml
@@ -14,6 +14,18 @@ on:
         required: false
         type: string
         default: '["ubuntu-24.04", "ubuntu-24.04-arm"]'
+      gar_image:
+        required: false
+        type: string
+        default: ""
+      file:
+        required: false
+        type: string
+        default: ""
+      build_args:
+        required: false
+        type: string
+        default: ""
 jobs:
   build:
     strategy:
@@ -38,6 +50,18 @@ jobs:
             echo "Valid docker context"
           else
             echo "Invalid docker context"
+            exit 1
+          fi
+          if [[ "${{ inputs.gar_image }}" =~ $regex ]]; then
+            echo "Valid GAR image name"
+          else
+            echo "Invalid GAR image name"
+            exit 1
+          fi
+          if [[ "${{ inputs.file }}" =~ $regex ]]; then
+            echo "Valid Dockerfile path"
+          else
+            echo "Invalid Dockerfile path"
             exit 1
           fi
 
@@ -68,9 +92,11 @@ jobs:
         uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7
         with:
           context: ${{ inputs.context }}
+          file: ${{ inputs.file }}
           build-args: |
             TARGETARCH=${{ steps.vars.outputs.platform }}
             LEHIGH_TAG=${{ steps.vars.outputs.tag }}
+            ${{ inputs.build_args }}
           push: true
           cache-from: ${{ steps.vars.outputs.cache-from }}
           cache-to: ${{ steps.vars.outputs.cache-to }}
@@ -91,6 +117,35 @@ jobs:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Set up Cloud SDK
+        if: inputs.gar_image != ''
+        uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3
+        with:
+          version: "latest"
+
+      - name: Authenticate to Google Cloud
+        if: inputs.gar_image != ''
+        id: "auth"
+        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3
+        with:
+          workload_identity_provider: ${{ secrets.GCLOUD_OIDC_POOL }}
+          service_account: ${{ secrets.GSA }}
+          token_format: "access_token"
+
+      - name: Configure gcloud
+        if: inputs.gar_image != ''
+        run: |
+          gcloud config set project ${{ secrets.GCLOUD_PROJECT }}
+          gcloud config set disable_prompts true
+
+      - name: GAR login
+        if: inputs.gar_image != ''
+        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
+        with:
+          registry: "us-docker.pkg.dev"
+          username: "oauth2accesstoken"
+          password: "${{ steps.auth.outputs.access_token }}"
 
       - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
         with:
@@ -124,8 +179,14 @@ jobs:
             tags="$tags ${image}:${tag}-${platform}"
           done
 
+          extra_tags=""
+          if [[ -n "${{ inputs.gar_image }}" ]]; then
+            extra_tags="-t ${{ inputs.gar_image }}:${{ steps.vars.outputs.tag }}"
+          fi
+
           docker buildx imagetools create \
             -t "${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.tag }}" \
+            $extra_tags \
             $tags
         env:
           DOCKER_IMAGE: ${{ steps.vars.outputs.image }}
