Allow pushing to GAR too

diff --git a/.github/workflows/build-push-ghcr.yaml b/.github/workflows/build-push-ghcr.yaml
--- a/.github/workflows/build-push-ghcr.yaml
+++ b/.github/workflows/build-push-ghcr.yaml
@@ -14,6 +14,10 @@ on:
         required: false
         type: string
         default: '["ubuntu-24.04", "ubuntu-24.04-arm"]'
+      gar_image:
+        required: false
+        type: string
+        default: ""
 jobs:
   build:
     strategy:
@@ -38,6 +42,12 @@ jobs:
             echo "Valid docker context"
           else
             echo "Invalid docker context"
+            exit 1
+          fi
+          if [[ "${{ inputs.gar_image }}" =~ $regex ]]; then
+            echo "Valid GAR image name"
+          else
+            echo "Invalid GAR image name"
             exit 1
           fi
 
@@ -92,6 +102,35 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
+      - name: Set up Cloud SDK
+        if: inputs.gar_image != ''
+        uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3
+        with:
+          version: "latest"
+
+      - name: Authenticate to Google Cloud
+        if: inputs.gar_image != ''
+        id: "auth"
+        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3
+        with:
+          workload_identity_provider: ${{ secrets.GCLOUD_OIDC_POOL }}
+          service_account: ${{ secrets.GSA }}
+          token_format: "access_token"
+
+      - name: Configure gcloud
+        if: inputs.gar_image != ''
+        run: |
+          gcloud config set project ${{ secrets.GCLOUD_PROJECT }}
+          gcloud config set disable_prompts true
+
+      - name: GAR login
+        if: inputs.gar_image != ''
+        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
+        with:
+          registry: "us-docker.pkg.dev"
+          username: "oauth2accesstoken"
+          password: "${{ steps.auth.outputs.access_token }}"
+
       - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
         with:
           repository: lehigh-university-libraries/gha
@@ -124,8 +163,14 @@ jobs:
             tags="$tags ${image}:${tag}-${platform}"
           done
 
+          extra_tags=""
+          if [[ -n "${{ inputs.gar_image }}" ]]; then
+            extra_tags="-t ${{ inputs.gar_image }}:${{ steps.vars.outputs.tag }}"
+          fi
+
           docker buildx imagetools create \
             -t "${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.tag }}" \
+            $extra_tags \
             $tags
         env:
           DOCKER_IMAGE: ${{ steps.vars.outputs.image }}
